name: dj_bot
description: DJ assistant telegram bot
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  hive: ^2.2.3
  meta: ^1.8.0
  teledart: ^0.3.4

dev_dependencies:
  build_runner: ^2.2.0
  hive_generator: ^1.1.3
  lints: ^2.0.0
  test: ^1.21.4
