name: dj_bot
description: DJ assistant telegram bot
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  meta: ^1.8.0
  teledart: ^0.3.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
