name: dj_bot
description: DJ assistant telegram bot
version: 1.0.0

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  hive: ^2.2.3
  json_annotation: ^4.6.0
  logging: ^1.0.2
  meta: ^1.8.0
  teledart: ^0.3.4

dev_dependencies:
  build_runner: ^2.2.0
  environment_config: ^3.1.0
  hive_generator: ^1.1.3
  json_serializable: ^6.3.1
  lints: ^2.0.0
  test: ^1.21.4
